# Désactiver le montage automatique du token SA pour tous les microservices
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: dev
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservices-sa
  namespace: prod
automountServiceAccountToken: false
---
# Role minimal pour les microservices
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microservice-minimal
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]