# ── Identification projet LOCAL ──
sonar.projectKey=pfe_devsecops_local
sonar.projectName=PFE DevSecOps Local

# ── Serveur local ──
sonar.host.url=http://localhost:9000
sonar.token=squ_81df951a0dc8458668d1fc6fcc011157c1944472

# ── Code ──
sonar.sources=src

# ── Exclusions ──
sonar.exclusions=**/*.java,**/node_modules/**,**/*.test.*,**/build/**,**/dist/**,**/*.pb.go,**/vendor/**,**/__pycache__/**