# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
  annotations:
    checkov.io/skip100: CKV_K8S_22=Might break file writes
    checkov.io/skip101: CKV_K8S_28=Capabilities needed
    checkov.io/skip102: CKV_K8S_37=Default seccomp is fine
    checkov.io/skip103: CKV_K8S_43=Using latest tags for development
    checkov.io/skip104: CKV_K8S_8=No liveness probe available
    checkov.io/skip105: CKV_K8S_9=No readiness probe available
    checkov.io/skip106: CKV_K8S_10=No CPU requests
    checkov.io/skip107: CKV_K8S_11=No CPU limits
    checkov.io/skip108: CKV_K8S_12=No Memory requests
    checkov.io/skip109: CKV_K8S_13=No Memory limits
    checkov.io/skip110: CKV_K8S_14=No CPU limit
    checkov.io/skip111: CKV_K8S_15=No Memory limit
    checkov.io/skip200: CKV_K8S_21=Default namespace is used by design in this 
      architecture
    checkov.io/skip201: CKV_K8S_31=Seccomp profile might break legacy apps
    checkov.io/skip202: CKV_K8S_40=UID 1000 is used instead of 10000 to preserve
      file permissions
    checkov.io/skip203: CKV_K8S_23=Some containers require root
    checkov.io/skip204: CKV_K8S_29=Security context not required for patches
    checkov.io/skip205: CKV_K8S_38=Service account tokens are managed explicitly
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: productcatalogservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: registry.localhost:5000/productcatalogservice:latest
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          initialDelaySeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
          grpc:
            port: 3550
        livenessProbe:
          initialDelaySeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
          grpc:
            port: 3550
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  labels:
    app: productcatalogservice
  annotations:
    checkov.io/skip100: CKV_K8S_22=Might break file writes
    checkov.io/skip101: CKV_K8S_28=Capabilities needed
    checkov.io/skip102: CKV_K8S_37=Default seccomp is fine
    checkov.io/skip103: CKV_K8S_43=Using latest tags for development
    checkov.io/skip104: CKV_K8S_8=No liveness probe available
    checkov.io/skip105: CKV_K8S_9=No readiness probe available
    checkov.io/skip106: CKV_K8S_10=No CPU requests
    checkov.io/skip107: CKV_K8S_11=No CPU limits
    checkov.io/skip108: CKV_K8S_12=No Memory requests
    checkov.io/skip109: CKV_K8S_13=No Memory limits
    checkov.io/skip110: CKV_K8S_14=No CPU limit
    checkov.io/skip111: CKV_K8S_15=No Memory limit
    checkov.io/skip200: CKV_K8S_21=Default namespace is used by design in this 
      architecture
    checkov.io/skip201: CKV_K8S_31=Seccomp profile might break legacy apps
    checkov.io/skip202: CKV_K8S_40=UID 1000 is used instead of 10000 to preserve
      file permissions
    checkov.io/skip203: CKV_K8S_23=Some containers require root
    checkov.io/skip204: CKV_K8S_29=Security context not required for patches
    checkov.io/skip205: CKV_K8S_38=Service account tokens are managed explicitly
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice
  annotations:
    checkov.io/skip100: CKV_K8S_22=Might break file writes
    checkov.io/skip101: CKV_K8S_28=Capabilities needed
    checkov.io/skip102: CKV_K8S_37=Default seccomp is fine
    checkov.io/skip103: CKV_K8S_43=Using latest tags for development
    checkov.io/skip104: CKV_K8S_8=No liveness probe available
    checkov.io/skip105: CKV_K8S_9=No readiness probe available
    checkov.io/skip106: CKV_K8S_10=No CPU requests
    checkov.io/skip107: CKV_K8S_11=No CPU limits
    checkov.io/skip108: CKV_K8S_12=No Memory requests
    checkov.io/skip109: CKV_K8S_13=No Memory limits
    checkov.io/skip110: CKV_K8S_14=No CPU limit
    checkov.io/skip111: CKV_K8S_15=No Memory limit
    checkov.io/skip200: CKV_K8S_21=Default namespace is used by design in this 
      architecture
    checkov.io/skip201: CKV_K8S_31=Seccomp profile might break legacy apps
    checkov.io/skip202: CKV_K8S_40=UID 1000 is used instead of 10000 to preserve
      file permissions
    checkov.io/skip203: CKV_K8S_23=Some containers require root
    checkov.io/skip204: CKV_K8S_29=Security context not required for patches
    checkov.io/skip205: CKV_K8S_38=Service account tokens are managed explicitly
