# ── Identification (compatible Cloud + Local) ──
sonar.projectKey=Nizarartuol_pfe_devsecops_local
sonar.organization=nizarartuol

# ── Code ──
sonar.sources=src
sonar.sourceEncoding=UTF-8

# ── Exclusions ──
sonar.exclusions=**/*.java,**/node_modules/**,**/*.test.*,**/build/**,**/dist/**,**/*.pb.go,**/vendor/**,**/__pycache__/**