{
 "title": "Microservices Overview - ArgoCD Namespace",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU par Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"argocd\", container!=\"\"}[2m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM par Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"argocd\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de Pod",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"argocd\"}) by (created_by_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restarts totaux",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"argocd\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Totale namespace",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"argocd\", container!=\"\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}