# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
components:
# - components/cymbal-branding
# - components/google-cloud-operations
# - components/memorystore
# - components/network-policies
# - components/non-public-frontend
# - components/service-accounts
# - components/alloydb
# - components/single-shared-session
# - components/spanner
# - components/service-mesh-istio
# - components/without-loadgenerator
# These must be run last and in this order
# - components/container-images-tag
# - components/container-images-tag-suffix
- components/container-images-registry

# Override image repository to use local k3d registry
images:
- name: adservice
  newName: registry.localhost:5000/adservice
  newTag: latest
- name: cartservice
  newName: registry.localhost:5000/cartservice
  newTag: latest
- name: checkoutservice
  newName: registry.localhost:5000/checkoutservice
  newTag: latest
- name: currencyservice
  newName: registry.localhost:5000/currencyservice
  newTag: latest
- name: emailservice
  newName: registry.localhost:5000/emailservice
  newTag: latest
- name: frontend
  newName: registry.localhost:5000/frontend
  newTag: latest
- name: loadgenerator
  newName: registry.localhost:5000/loadgenerator
  newTag: latest
- name: paymentservice
  newName: registry.localhost:5000/paymentservice
  newTag: latest
- name: productcatalogservice
  newName: registry.localhost:5000/productcatalogservice
  newTag: latest
- name: recommendationservice
  newName: registry.localhost:5000/recommendationservice
  newTag: latest
- name: shippingservice
  newName: registry.localhost:5000/shippingservice
  newTag: latest
metadata:
  annotations:
    checkov.io/skip100: CKV_K8S_22=Might break file writes
    checkov.io/skip101: CKV_K8S_28=Capabilities needed
    checkov.io/skip102: CKV_K8S_37=Default seccomp is fine
    checkov.io/skip103: CKV_K8S_43=Using latest tags for development
    checkov.io/skip104: CKV_K8S_8=No liveness probe available
    checkov.io/skip105: CKV_K8S_9=No readiness probe available
    checkov.io/skip106: CKV_K8S_10=No CPU requests
    checkov.io/skip107: CKV_K8S_11=No CPU limits
    checkov.io/skip108: CKV_K8S_12=No Memory requests
    checkov.io/skip109: CKV_K8S_13=No Memory limits
    checkov.io/skip110: CKV_K8S_14=No CPU limit
    checkov.io/skip111: CKV_K8S_15=No Memory limit
